#Profile: dev
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  flyway:
    enabled: true
