#Default properties

server:
  servlet:
    context-path: /api

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:resources/db/migration

